### ISSUE TITLE
I have access to AWS and Lambda - I am at the 'create function' page... how do I install this?

### ISSUE THREAD

**Issue by pperrin** [mahboubii/serverless-mercury-parser#1]

**Comment by mahboubii** [comment]
@pperrin checkout https://serverless.com/framework/docs/providers/aws/guide/quick-start/

**Comment by pperrin** [comment]
@mahboubii Cheers - I have serverless installed locally and have setup the user/account on AWS and added the credentials to my local serverless install, installed your package from git, done an npm install now tried a deploy and get...

  The CloudFormation template is invalid: [/Resources/ParserLambdaFunction/Type/Environment/Variables/SECRET_KEY] 'null' values are not allowed in templates

Getting closer...

**Comment by mahboubii** [comment]
@pperrin good job, just pushed a fix for null KEY, try `git pull` and deploy again

**Comment by pperrin** [comment]
@mahboubii I installed it using 
`serverless install -u https://github.com/mahboubii/serverless-mercury-parser --name mercury`

It doesn't seem to be recognised as a git directory - I can delete the directory and install again (but that would mean redoing the npm install...)... or is there a different way of getting a pull in serverless?

**Comment by mahboubii** [comment]
@pperrin yo have to 
`git clone https://github.com/mahboubii/serverless-mercury-parser.git`
`cd serverless-mercury-parser.git`
`yarn`
`sls deploy`

**Comment by pperrin** [comment]
I don't know anything about yarn, and am already using two apps I have not used before... so I deleted the directory, re did the install and the npm install... I guess there must be a serverless command to update a service from a git repository, but it will have to wait! :)

Anyway - it all installed and works! I just need to change my code that is calling the mercury public server to call my own now.

Cheers!
